// AUTO-GENERATED by train/export.py — do not hand-edit this file.
// To change behavior: edit train/gaze_model_template.js (this file's source
// template), train/normalize.py (must match the normalizer logic below
// exactly), or collect/features.js, then rerun `python train/export.py`.
//
// Single-file ES module, zero external dependencies. Usage:
//   import { GazeModel } from './gaze-model.js';
//   const model = await GazeModel.load('./gaze-model.json');
//   const p = model.predict(faceLandmarks, faceBlendshapes); // blendshapes optional
//   // => { x, y, confidence, zone } — x,y in 0-1 screen coordinates,
//   //    zone = { col: 0-2, row: 0-1 } — use zone for anything but the
//   //    coarsest UI, see README for why.
//
// No quickCalibrate, no localStorage: per-user adaptation now happens
// automatically via a running per-user statistic (plain cumulative average
// below) that needs no calibration points or labels at all — just observed
// frames. An earlier version tried EMA with posture-change-triggered
// acceleration; measured (train/compare_normalizers.py) as worse both
// overall AND specifically in the post-posture-change window it was meant
// to help — removed rather than shipped on unmeasured promise.

// ============================================================
// Feature extraction — verbatim copy of collect/features.js,
// spliced in at export time. This is intentionally the exact
// same code, not a reimplementation: collection and inference
// must compute features identically.
// ============================================================
// features.js
//
// Pure feature extraction from a single MediaPipe FaceLandmarker result
// (478-point face mesh, iris refinement on, indices 468-477 = both irises).
//
// This is the single source of truth for turning raw landmarks + blendshapes
// into the numeric feature vector used everywhere else in this project:
// collect/index.html uses it while recording training data, and the same
// file is copied byte-for-byte into deliver/ so inference uses the exact
// same math. Do not duplicate this logic anywhere else.

// Canonical MediaPipe Face Mesh landmark indices. "left"/"right" follow
// MediaPipe's own convention: the subject's own left/right, not the
// viewer's left/right on screen.
const LM = {
  noseTip: 1,
  forehead: 10,
  chin: 152,
  leftFaceEdge: 234, // subject's left temple/cheek
  rightFaceEdge: 454, // subject's right temple/cheek

  // Right eye (subject's right)
  rightOuter: 33,
  rightInner: 133,
  rightUpperA: 159,
  rightUpperB: 158,
  rightLowerA: 145,
  rightLowerB: 153,
  rightIris: 468,

  // Left eye (subject's left)
  leftOuter: 263,
  leftInner: 362,
  leftUpperA: 386,
  leftUpperB: 385,
  leftLowerA: 374,
  leftLowerB: 380,
  leftIris: 473,
};

function dist(a, b) {
  const dx = a.x - b.x;
  const dy = a.y - b.y;
  return Math.sqrt(dx * dx + dy * dy);
}

function mid(a, b) {
  return { x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 };
}

function blendshapeScore(blendshapes, name) {
  if (!blendshapes || !blendshapes.length || !blendshapes[0].categories) return 0;
  const cat = blendshapes[0].categories.find((c) => c.categoryName === name);
  return cat ? cat.score : 0;
}

// Normalized position of the iris inside its eye socket.
// h: 0 at the outer corner, 1 at the inner corner.
// v: 0 at the upper lid, 1 at the lower lid.
function irisPosition(lm, outerIdx, innerIdx, upperAIdx, upperBIdx, lowerAIdx, lowerBIdx, irisIdx) {
  const outer = lm[outerIdx];
  const inner = lm[innerIdx];
  const upper = mid(lm[upperAIdx], lm[upperBIdx]);
  const lower = mid(lm[lowerAIdx], lm[lowerBIdx]);
  const iris = lm[irisIdx];

  const hSpan = dist(outer, inner) || 1e-6;
  const vSpan = dist(upper, lower) || 1e-6;

  return {
    h: dist(iris, outer) / hSpan,
    v: dist(iris, upper) / vSpan,
  };
}

// Eye-aspect-ratio style openness: mean eyelid gap / eye width.
function eyeOpenness(lm, outerIdx, innerIdx, upperAIdx, upperBIdx, lowerAIdx, lowerBIdx) {
  const width = dist(lm[outerIdx], lm[innerIdx]) || 1e-6;
  const gapA = dist(lm[upperAIdx], lm[lowerAIdx]);
  const gapB = dist(lm[upperBIdx], lm[lowerBIdx]);
  return (gapA + gapB) / 2 / width;
}

// Lightweight ratio-based head pose proxy. Not a real 3D pose (no
// solvePnP / camera model) — just signed ratios that are ~0 when facing
// the camera straight on and move monotonically with yaw/pitch. Good
// enough as a regression feature, not as a calibrated angle.
function headPose(lm) {
  const nose = lm[LM.noseTip];
  const leftEdge = lm[LM.leftFaceEdge];
  const rightEdge = lm[LM.rightFaceEdge];
  const forehead = lm[LM.forehead];
  const chin = lm[LM.chin];

  const faceWidth = dist(leftEdge, rightEdge) || 1e-6;
  const faceHeight = dist(forehead, chin) || 1e-6;

  const midX = (leftEdge.x + rightEdge.x) / 2;
  const midY = (forehead.y + chin.y) / 2;

  return {
    yaw: (nose.x - midX) / faceWidth,
    pitch: (nose.y - midY) / faceHeight,
  };
}

// landmarks: array of 478 {x,y,z} normalized points (result.faceLandmarks[0])
// blendshapes: result.faceBlendshapes (array with .categories), or null/undefined
// Returns null if landmarks are missing/incomplete (caller should skip the frame).
function extractFeatures(landmarks, blendshapes) {
  if (!landmarks || landmarks.length < 478) {
    return null;
  }

  const right = irisPosition(
    landmarks,
    LM.rightOuter, LM.rightInner,
    LM.rightUpperA, LM.rightUpperB,
    LM.rightLowerA, LM.rightLowerB,
    LM.rightIris
  );
  const left = irisPosition(
    landmarks,
    LM.leftOuter, LM.leftInner,
    LM.leftUpperA, LM.leftUpperB,
    LM.leftLowerA, LM.leftLowerB,
    LM.leftIris
  );

  const openRight = eyeOpenness(
    landmarks, LM.rightOuter, LM.rightInner,
    LM.rightUpperA, LM.rightUpperB, LM.rightLowerA, LM.rightLowerB
  );
  const openLeft = eyeOpenness(
    landmarks, LM.leftOuter, LM.leftInner,
    LM.leftUpperA, LM.leftUpperB, LM.leftLowerA, LM.leftLowerB
  );

  const { yaw, pitch } = headPose(landmarks);

  // Distance between the two eye tails (outer corners), in MediaPipe's
  // native normalized [0,1] image space. Deliberately NOT divided by any
  // other face measurement: this value grows as the face gets closer to
  // the camera, so it doubles as a rough proxy for distance-to-screen.
  // Dividing it by another face-width measurement would cancel that
  // signal out.
  const interocular = dist(landmarks[LM.rightOuter], landmarks[LM.leftOuter]);

  return {
    h_left: left.h,
    v_left: left.v,
    h_right: right.h,
    v_right: right.v,
    open_left: openLeft,
    open_right: openRight,
    yaw,
    pitch,
    interocular,
    blink_left: blendshapeScore(blendshapes, 'eyeBlinkLeft'),
    blink_right: blendshapeScore(blendshapes, 'eyeBlinkRight'),
  };
}


// ============================================================
// Causal per-user normalization: running mean/var (Welford), shrunk toward
// a population prior with virtual weight k. No posture-change handling —
// deliberately simple; a version with EMA + posture-triggered fast
// adaptation measured worse on real data (see repo history). Must match
// train/normalize.py exactly — the parity test replays an identical frame
// sequence through both and compares every step.
// ============================================================
const BASE_FEATURES_ORDER = ['h_left', 'v_left', 'h_right', 'v_right', 'open_left', 'open_right', 'yaw', 'pitch', 'interocular'];

class CumulativeNormalizer {
  constructor(priorMean, priorStd, k) {
    this.priorMean = priorMean.slice();
    this.priorStd = priorStd.slice();
    this.runningMean = priorMean.slice();
    this.runningM2 = priorMean.map(() => 0);
    this.n = 0;
    this.k = k;
  }

  // x: raw base feature array (9,), in BASE_FEATURES_ORDER. Normalizes
  // using the state as of BEFORE this frame (predict-then-update), then
  // advances the state for next time — so one outlier frame can't skew
  // its own normalization.
  step(x) {
    const runningVar = this.n > 0 ? this.runningM2.map((v) => v / this.n) : this.runningM2.map(() => 0);
    const effMean = this.runningMean.map((m, i) => (this.n * m + this.k * this.priorMean[i]) / (this.n + this.k));
    const effVar = runningVar.map((v, i) => (this.n * v + this.k * this.priorStd[i] * this.priorStd[i]) / (this.n + this.k));
    const effStd = effVar.map((v) => Math.sqrt(Math.max(v, 1e-8)));
    const normalized = x.map((v, i) => (v - effMean[i]) / effStd[i]);

    this.n += 1;
    const delta = x.map((v, i) => v - this.runningMean[i]);
    this.runningMean = this.runningMean.map((m, i) => m + delta[i] / this.n);
    const delta2 = x.map((v, i) => v - this.runningMean[i]);
    this.runningM2 = this.runningM2.map((m2, i) => m2 + delta[i] * delta2[i]);

    return normalized;
  }
}

// ============================================================
// Feature engineering — must match train/common.py::engineer_features
// column-for-column and in the same order (that order is how the
// scaler mean/scale and model weights were fit).
// ============================================================
function engineerFeatureVector(feat) {
  const { h_left, v_left, h_right, v_right, open_left, open_right, yaw, pitch, interocular } = feat;
  return [
    h_left, v_left, h_right, v_right, open_left, open_right, yaw, pitch, interocular,
    h_left * h_left, v_left * v_left, h_left * v_left,
    h_left * yaw, v_left * yaw, h_left * pitch, v_left * pitch, h_left * interocular, v_left * interocular,
    h_right * h_right, v_right * v_right, h_right * v_right,
    h_right * yaw, v_right * yaw, h_right * pitch, v_right * pitch, h_right * interocular, v_right * interocular,
  ];
}

function standardize(vec, mean, scale) {
  return vec.map((v, i) => (v - mean[i]) / scale[i]);
}

function clamp01(v) {
  return Math.max(0, Math.min(1, v));
}

// ============================================================
// Hand-written forward passes (no onnxruntime/tensorflow.js). x and y are
// now INDEPENDENT single-output models (x: Random Forest, y: Ridge — see
// README for why they're not the same model), each with its own scaler.
// ============================================================
function forwardRidgeSingle(xStd, spec) {
  let s = spec.intercept;
  for (let i = 0; i < xStd.length; i++) s += spec.coef[i] * xStd[i];
  return s;
}

function forwardRandomForestSingle(xStd, spec) {
  let sum = 0;
  for (const tree of spec.trees) {
    let node = 0;
    while (tree.left[node] !== -1) {
      node = xStd[tree.feature[node]] <= tree.threshold[node] ? tree.left[node] : tree.right[node];
    }
    sum += tree.value[node];
  }
  return sum / spec.trees.length;
}

function forwardModel(xStd, spec) {
  if (spec.type === 'ridge') return forwardRidgeSingle(xStd, spec);
  if (spec.type === 'random_forest') return forwardRandomForestSingle(xStd, spec);
  throw new Error('unknown model type in gaze-model.json: ' + spec.type);
}

// ============================================================
// Zone: coarse 3-column x 2-row grid. The model's real accuracy (~150px
// horizontal, ~210px vertical on a 1920x1080 screen) does not support a
// finer grid on the vertical axis — see README. Compute from CLAMPED x,y.
// ============================================================
function computeZone(x, y) {
  const col = Math.max(0, Math.min(2, Math.floor(x * 3)));
  const row = Math.max(0, Math.min(1, Math.floor(y * 2)));
  return { col, row };
}

// ============================================================
// Confidence: how much to trust this frame's {x,y,zone}.
// ============================================================
function poseFactor(value, range) {
  const [lo, hi] = range;
  if (value >= lo && value <= hi) return 1.0;
  const span = Math.max(hi - lo, 1e-6);
  const overflow = value < lo ? lo - value : value - hi;
  const ratio = overflow / span;
  return Math.max(0.1, 1 - ratio * 2);
}

function computeConfidence(feat, spec) {
  let conf = 1.0;
  const blinkScore = Math.max(feat.blink_left, feat.blink_right);
  if (blinkScore > 0.5) conf *= 0.15; // eyes closed: never trained on this, don't trust it
  conf *= poseFactor(feat.yaw, spec.yaw_range);
  conf *= poseFactor(feat.pitch, spec.pitch_range);
  return clamp01(conf);
}

// ============================================================
// One Euro Filter (Casiez et al. 2012) — smooths jittery per-frame
// predictions into a stable moving point without adding much lag.
// ============================================================
class LowPassFilter {
  constructor() {
    this._initialized = false;
    this._y = 0;
  }
  filter(x, alpha) {
    const y = this._initialized ? alpha * x + (1 - alpha) * this._y : x;
    this._initialized = true;
    this._y = y;
    return y;
  }
  lastValue() {
    return this._y;
  }
}

class OneEuroFilter {
  constructor(minCutoff = 1.0, beta = 0.007, dCutoff = 1.0) {
    this.minCutoff = minCutoff;
    this.beta = beta;
    this.dCutoff = dCutoff;
    this._xFilter = new LowPassFilter();
    this._dxFilter = new LowPassFilter();
    this._initialized = false;
  }
  _alpha(cutoff, dt) {
    const tau = 1 / (2 * Math.PI * cutoff);
    return 1 / (1 + tau / dt);
  }
  filter(x, dt) {
    dt = Math.max(dt, 1e-3);
    const dx = this._initialized ? (x - this._xFilter.lastValue()) / dt : 0;
    this._initialized = true;
    const edx = this._dxFilter.filter(dx, this._alpha(this.dCutoff, dt));
    const cutoff = this.minCutoff + this.beta * Math.abs(edx);
    return this._xFilter.filter(x, this._alpha(cutoff, dt));
  }
}

// ============================================================
// Public API
// ============================================================
class GazeModel {
  constructor(spec) {
    this.spec = spec;
    this.normalizer = new CumulativeNormalizer(spec.population_prior.mean, spec.population_prior.std, spec.normalizer.k);
    this._filterX = new OneEuroFilter();
    this._filterY = new OneEuroFilter();
    this._lastT = null;
  }

  static async load(url) {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`failed to load ${url}: ${res.status}`);
    const spec = await res.json();
    return new GazeModel(spec);
  }

  // Deterministic GIVEN the normalizer's current state — but that state is
  // itself stateful across calls (this is what makes per-user adaptation
  // work without calibration points). No smoothing here; that's what
  // predict() adds on top. This is what the parity test replays a fixed
  // frame sequence through and compares step-by-step, since normalization
  // — unlike smoothing — is core math, not a cosmetic post-process.
  predictRaw(landmarks, blendshapes) {
    const feat = extractFeatures(landmarks, blendshapes);
    if (!feat) return { x: null, y: null, confidence: 0, zone: null };

    const baseVec = BASE_FEATURES_ORDER.map((name) => feat[name]);
    const normalized = this.normalizer.step(baseVec);
    const normFeat = {};
    BASE_FEATURES_ORDER.forEach((name, i) => { normFeat[name] = normalized[i]; });

    const vec = engineerFeatureVector(normFeat);
    const xStdForX = standardize(vec, this.spec.x_model.scaler_mean, this.spec.x_model.scaler_scale);
    const xStdForY = standardize(vec, this.spec.y_model.scaler_mean, this.spec.y_model.scaler_scale);
    const x = clamp01(forwardModel(xStdForX, this.spec.x_model));
    const y = clamp01(forwardModel(xStdForY, this.spec.y_model));

    const confidence = computeConfidence(feat, this.spec);
    const zone = computeZone(x, y);
    return { x, y, confidence, zone };
  }

  // The one you actually use: raw prediction + smoothing.
  predict(landmarks, blendshapes) {
    const raw = this.predictRaw(landmarks, blendshapes);
    if (raw.x === null) {
      this._lastT = null; // don't let smoothing bridge across a no-face gap
      return raw;
    }
    const now = typeof performance !== 'undefined' ? performance.now() : Date.now();
    const dt = this._lastT == null ? 1 / 30 : Math.max((now - this._lastT) / 1000, 1e-3);
    this._lastT = now;
    const x = clamp01(this._filterX.filter(raw.x, dt));
    const y = clamp01(this._filterY.filter(raw.y, dt));
    return { x, y, confidence: raw.confidence, zone: computeZone(x, y) };
  }
}

export { GazeModel };
